services:
  zilean:
    image: itsayushsehrawat/zilean:latest
    restart: unless-stopped
    container_name: zilean
    tty: true
    ports:
      - "8181:8181"
    environment:
      Zilean__EnableDashboard: true
      Zilean__Database__ConnectionString: Host=zilean_postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Include Error Detail=true;Timeout=30;CommandTimeout=3600
      Zilean__Imdb__UseAllCores: true
      Zilean__Imdb__UseLucene: true
      Zilean__Parsing__BatchSize: 100000
      Zilean__Dmm_ScrapeSchedule: 32 * * * *
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - ${DOCKER_DATA_DIR}/zilean/tmp:/tmp
    depends_on:
      zilean_postgres:
        condition: service_healthy
    healthcheck:
      test: curl --connect-timeout 10 --silent --show-error --fail http://localhost:8181/healthchecks/ping
      timeout: 60s
      interval: 30s
      retries: 10

  zilean_postgres:
    image: postgres:17.2-alpine
    container_name: zilean_postgres
    restart: unless-stopped
    shm_size: 2G
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${DOCKER_DATA_DIR}/zilean/db:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 5s
      retries: 5
