version: "3.9"

volumes:
  zilean_data:
  zilean-pg-data:

services:
  zilean:
    image: itsayushsehrawat/zilean:latest
    container_name: zilean
    restart: unless-stopped
    tty: true

    ports:
      - "${ZILEAN_PORT}:8181"

    volumes:
      - zilean_data:/app/data
      # - ./settings.json:/app/data/settings.json

    environment:
      Zilean__Database__ConnectionString: Host=zilean-postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GITHUB_TOKEN: ${GITHUB_TOKEN}

      # Optional ingestion config
      # Zilean__Ingestion__EnableScraping: ${ENABLE_SCRAPING}
      # Zilean__Ingestion__ScrapeSchedule: ${SCRAPE_SCHEDULE}

    healthcheck:
      test: curl --connect-timeout 10 --silent --show-error --fail http://localhost:8181/healthchecks/ping
      timeout: 60s
      interval: 30s
      retries: 10

    depends_on:
      zilean-postgres:
        condition: service_healthy


  zilean-postgres:
    image: postgres:16.3-alpine3.20
    container_name: zilean-postgres
    restart: unless-stopped
    shm_size: 2g

    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - zilean-pg-data:/var/lib/postgresql/data/pgdata

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
