services:
  minio:
    image: minio/minio:latest
    container_name: minio_global
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_LAN_IP}:${MINIO_PORT}:9000"
      - "${MINIO_LAN_IP}:${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - minionet

volumes:
  minio_data:

networks:
  minionet:
    driver: bridge
